{% set version = "2.13.1" %}
{% set sha256 = "d3672d6a676f284c13a89d632b07b441f234caf0748e59271a18464a84172040" %}

package:
  name: imageio
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/imageio/imageio-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
  entry_points:
    - imageio_download_bin = imageio.__main__:download_bin_main
    - imageio_remove_bin = imageio.__main__:remove_bin_main

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - numpy
    - pillow >=8.3.2

test:
  requires:
    - pytest
    - pytest-cov
    - invoke
    - psutil
    - tifffile
  imports:
    - imageio
  source_files:
    - tests/
    - .coveragerc
  commands:
    - imageio_download_bin -h
    - imageio_remove_bin -h
    - PYTEST_ADDOPTS="--ignore=tests/test_ffmpeg.py" invoke test --unit

about:
  home: https://imageio.github.io
  doc_url: https://imageio.readthedocs.io
  dev_url: https://github.com/imageio/imageio
  summary: A Python library for reading and writing image data
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anjos
    - almarklein
    - blink1073
    - jni
