{% set version = "2.18.0" %}

package:
  name: imageio
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/imageio/imageio-{{ version }}.tar.gz
  sha256: 090898c48532631ab11c74ae743e64c24dabda45c16db46f7e3bec9e2d8f422f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
  entry_points:
    - imageio_download_bin = imageio.__main__:download_bin_main
    - imageio_remove_bin = imageio.__main__:remove_bin_main

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - numpy >=1.20.0
    - pillow >=8.3.2

test:
  requires:
    - git
    - pytest
    - psutil
    - tifffile
    - gdal
    - astropy
    - freeimage
    - fsspec
    - requests
  imports:
    - imageio
  source_files:
    - tests/
  commands:
    - imageio_download_bin -h
    - imageio_remove_bin -h
    - pytest -sv tests/ -k "not test_findlib2"

about:
  home: https://imageio.github.io
  doc_url: https://imageio.readthedocs.io
  dev_url: https://github.com/imageio/imageio
  summary: A Python library for reading and writing image data
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anjos
    - almarklein
    - blink1073
    - jni
